#!/bin/bash

source ./bash-colors

(echo -e "${GREEN}Installing Docker ...${RESET_COLOR}" && \
apt-get update && \
apt-get install -y apt-transport-https \
	ca-certificates \
	curl \
	gnupg-agent \
	software-properties-common && \
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - && \
echo -e "${GREEN}Setting up stable repository ...${RESET_COLOR}" && \
add-apt-repository -y \
	"deb [arch=arm64] https://download.docker.com/linux/debian \
	$(lsb_release -cs) \
	stable" && \
echo -e "${GREEN}Installing Docker Engine and containerd ...${RESET_COLOR}" && \
apt-get update && \
apt-get install -y docker-ce docker-ce-cli containerd.io && \
docker --version && \
echo -e "${GREEN}Docker has been installed!!!${RESET_COLOR}") || \
echo -e "${RED}Ooops something went wrong ...${RESET_COLOR}"
